changes to h5 loaders to have res2rad
dermen/resnet pull request #14
Opened 2023-03-08 23:18 UTC by rrstofer

2023-03-08 23:18 UTC, rrstofer commented
It also has an additional L2 argument for PNG loaders so if the loss is L2, it can run normally!

2023-03-09 02:40 UTC, dermen requested changes
Looks good to support all 4 options in the PngDset class (invert /convert).

But regarding the h5 loader having a convert script, I dont think we need it now. You could though update the `sims/main.py` to store a one_over_radius in the labels , and then update `scripts/expand_labels.py` accordingly.

2023-03-09 02:40 UTC, dermen commented on loaders.py
> +            self.prop.loc[:, "reso"] = 1/self._convert_res2rad(self.prop.reso)
I think we need all 4 options: either use res, one_over_res, rad, one_over rad. You can then remove the assert on line 33 (now we will allow invert_res and convert_res to both be True). Then switch the order, such that inversion happens after conversion..

2023-03-09 02:40 UTC, dermen commented on loaders.py
> +            img_dat = img_dat.float()
remind me again what was happening here ? Why was this necessary?

2023-03-09 02:40 UTC, dermen commented on loaders.py
> +            img_dat = img_dat.float()
Also, I would change the variable `self.L2` to be something more descriptive, like `self.convert_to_float`..

2023-03-09 02:40 UTC, dermen commented on loaders.py
> +    def _convert_res2rad(self, res):
So if you look in `sims/main.py`, where the labels are created, you will notice a resolution -> radius conversion occurs `radius = reso2radius(params["reso"], DET, BEAM)`,  and this radius is stored in the hdf5 file. 

So one simply needs to create a dataset to point to it (see `scripts/expand_labels.py`.. Hence, I dont think we need this here.

2023-03-09 03:41 UTC, Sir-Teo commented on loaders.py
> +            img_dat = img_dat.float()
I changed this on my end also, cos for MESLoss, it only support the float datatype

2023-03-10 17:11 UTC, dermen commented
Added some updates. Basically, going forward lets simply use the net.py script. First, one must convert the Png data to HDF5 using the new script `resmos_to_hdf5.py`

```
python resmos_to_hdf5.py  $DD/png /data/dermen/num_reso_mos_B_icy1_icy2_cell_SGnum_pdbid_stolid.txt  $DD/resmos2.hdf5 --overwrite
```

Then, one can train on rad, one_over_rad, res, one_over_res, using e.g.:

```
python net.py 100 resmos2.hdf5 test_resmos2_h5 --lr 1e-4 --bs 16   --saveFreq 5 --arch res50 --labelName one_over_rad --loss L2 --testRange 0 500 --trainRange 500 2500 --momentum 0.9 
```

2023-03-10 17:15 UTC, dermen approved these changes

2023-03-10 17:19 UTC, merged